spring:
  datasource:
    url: jdbc:mysql://localhost/adc
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
server:
  port: 9000